default['logstash']['install_dir'] = '/opt'
default['logstash']['dir'] = "#{node['logstash']['install_dir']}/logstash"
default['logstash']['user'] = 'logstash'
default['logstash']['uid'] = nil # set to nil to let system pick
default['logstash']['group'] = 'logstash'
default['logstash']['gid'] = nil # set to nil to let system pick
default['logstash']['version'] = '1.4.0'
default['logstash']['url'] = "https://download.elasticsearch.org/logstash/logstash/logstash-#{node['logstash']['version']}.zip"
default['logstash']['homedir'] = '/var/lib/logstash'
default['logstash']['pid_dir'] = '/var/run/logstash'
default['logstash']['pid_file'] = '/var/run/logstash'
default['logstash']['log_file'] = '/var/log/logstash/logstash.log'
default['logstash']['conf_dir'] = '/etc/logstash/conf.d'